Changing scripts to use Vale instead of Spartan

diff --git a/everest b/everest
--- a/everest
+++ b/everest
@@ -20,6 +20,8 @@ FLEXDLL_URL=http://alain.frisch.fr/flexdll/$FLEXDLL_NAME.zip
 Z3_VERSION=4.5.0
 Z3_NAME=z3-$Z3_VERSION-x64-win
 Z3_URL=https://github.com/Z3Prover/z3/releases/download/z3-$Z3_VERSION/$Z3_NAME.zip
+NUGET_NAME=nuget
+NUGET_URL=https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
 VS_BIN=
 if [[ -v VS140COMNTOOLS ]]; then
   VS_BIN="$VS140COMNTOOLS"/../../VC/bin
@@ -113,6 +115,15 @@ write_z3_bashrc () {
   str="
     # This line automatically added by $0
     export PATH=$(pwd)/$Z3_NAME/bin:\$PATH"
+  eval "$str"
+  echo "$str" >> ~/.bashrc
+  magenta "Remember to run source ~/.bashrc in your terminal afterwards!"
+}
+
+write_nuget_bashrc () {
+  str="
+    # This line automatically added by $0
+    export PATH=$(pwd)/nuget/bin:\$PATH"
   eval "$str"
   echo "$str" >> ~/.bashrc
   magenta "Remember to run source ~/.bashrc in your terminal afterwards!"
@@ -413,6 +424,23 @@ OCAML
   fi
   echo "... correct z3 version detected"
 
+  # We need Nuget for Vale
+  if ! which nuget >/dev/null 2>&1 || [[ $(nuget | tr -d '\r\n'| sed s/Version.*//g) != "NuGet " ]]; then
+    red "ERROR: nuget doesn't seem to be installed"
+    if is_windows; then
+      magenta "Download it from the internet? [Yn]"
+      prompt_yes true "exit 1"
+      mkdir -p nuget/bin && cd nuget/bin && wget $NUGET_URL && cd ../..
+      magenta "Automatically customize ~/.bashrc with the nuget path? [Yn]"
+      prompt_yes write_nuget_bashrc true
+    else
+      echo "Hint: brew install nuget (OSX)"
+      echo "Hint: most recent versions available at https://dist.nuget.org"
+      exit 1
+    fi
+  fi
+  echo "... nuget found in PATH"
+
   # We bundle SCons in Vale, so Windows just needs a Python, while other
   # platforms want a system installation of Scons
   if is_windows; then
@@ -504,6 +532,18 @@ do_reset ()
   done
 }
 
+run_nuget () {
+  # This function is called in a subshell in a test context (via possibly_log)
+  # which means that -e is not inherited. Explicit failures here.
+  # OS-independnt scons. Pass $1 to scons.
+  cmd=$1
+  if is_windows; then
+    cd vale && nuget.exe restore ./tools/Vale/src/packages.config -PackagesDirectory tools/FsLexYacc $cmd || return 1
+  else
+    cd vale && nuget restore ./tools/Vale/src/packages.config -PackagesDirectory tools/FsLexYacc $cmd || return 1
+  fi
+}
+
 run_scons () {
   # This function is called in a subshell in a test context (via possibly_log)
   # which means that -e is not inherited. Explicit failures here.
@@ -519,19 +559,20 @@ run_scons () {
   fi
 }
 
-build_spartan () {
+build_vale () {
+  run_nuget
   run_scons # no arg if we're building.
 
-  # Import fresh crypto from Spartan into F*
+  # Import fresh crypto from Vale into F*
   cd FStar
   make -C examples/low-level/spartan_aes import || return 1
   if ! git diff --exit-code; then
-    magenta "New assemblies from Spartan, diff is above"
+    magenta "New assemblies from Vale, diff is above"
   fi
   cd ..
 }
 
-clean_spartan () {
+clean_vale () {
   run_scons "--clean"
 }
 
@@ -552,15 +593,15 @@ possibly_log () {
 setup_env () {
   if is_windows; then
     export FSTAR_HOME=$(cygpath -m $(pwd)/FStar)
-    export SPARTAN_HOME=$(cygpath -m $(pwd)/vale)
+    export VALE_HOME=$(cygpath -m $(pwd)/vale)
     export KREMLIN_HOME=$(cygpath -m $(pwd)/kremlin)
   else
     export FSTAR_HOME=$(pwd)/FStar
-    export SPARTAN_HOME=$(pwd)/vale
+    export VALE_HOME=$(pwd)/vale
     export KREMLIN_HOME=$(pwd)/kremlin
   fi
   magenta "exported FSTAR_HOME=$FSTAR_HOME"
-  magenta "exported SPARTAN_HOME=$SPARTAN_HOME"
+  magenta "exported VALE_HOME=$VALE_HOME"
   export PATH=$(pwd)/FStar/bin:$(pwd)/kremlin:$PATH
 
   local openssl_home=$(pwd)/FStar/ucontrib/CoreCrypto/ml/openssl
@@ -603,9 +644,9 @@ do_make ()
   echo -e "\n\n"
 
   separator
-  blue "Rebuilding Spartan"
-  if ! possibly_log "build_spartan" "spartan"; then
-    failed="$failed  Spartan\n"
+  blue "Rebuilding Vale"
+  if ! possibly_log "build_vale" "vale"; then
+    failed="$failed  Vale\n"
   fi
   separator
   echo -e "\n\n"
@@ -664,7 +705,7 @@ do_clean ()
     FStar/examples/low-level/{,spartan_aes,LowCProvider} mitls-fstar/src/{,tls}; do
     make -C "$d" clean
   done
-  clean_spartan
+  clean_vale
 }
 
 do_snapshot ()
